language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run backend sh -c "coverage run --source=app/api -m pytest && coverage report"